server:
  port: ${PORT:8761}
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30
    response-cache-update-interval-ms: 3000
  client:
    register-with-eureka: false
    fetch-registry: false
    disable-delta: true
  instance:
    prefer-ip-address: false
#spring:
#  cloud:
#    inetutils:
#      preferred-networks:
#        - 192.168
#      ignored-interfaces:
#        - eth1*